
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://hxzcxiaoyndomargozcl.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4emN4aWFveW5kb21hcmdvemNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTg3OTAsImV4cCI6MjA1NjE3NDc5MH0.7LitJpGV-XAUQE4i0WIT3PjmxrLD9YlCr3n1COc3ayA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export storage for direct access
export const storage = supabase.storage;

// Helper to generate a unique filename while preserving extension
export const generateUniqueFilename = (originalName: string): string => {
  const timestamp = new Date().getTime();
  const randomString = Math.random().toString(36).substring(2, 10);
  const extension = originalName.split('.').pop();
  const baseName = originalName.split('.').slice(0, -1).join('.');
  
  return `${baseName}_${timestamp}_${randomString}.${extension}`;
};

// Helper to check if a file with the same name exists in content table
export const fileExistsInContent = async (originalFilename: string): Promise<boolean> => {
  const { data, error } = await supabase
    .from('content')
    .select('id, original_filename')
    .eq('original_filename', originalFilename)
    .limit(1);
    
  if (error) {
    console.error("Error checking file existence:", error);
    return false;
  }
  
  return data && data.length > 0;
};

// Helper to replace a file in content table
export const replaceContentFile = async (
  originalFilename: string, 
  newContentUrl: string, 
  newThumbnailUrl: string | null,
  contentType: string,
  title: string,
  description: string | null,
  userId: string
): Promise<boolean> => {
  // First, get the existing content record
  const { data: existingContent, error: fetchError } = await supabase
    .from('content')
    .select('*')
    .eq('original_filename', originalFilename)
    .limit(1)
    .single();
  
  if (fetchError) {
    console.error("Error fetching existing content:", fetchError);
    return false;
  }

  // Now update the content record
  const { error: updateError } = await supabase
    .from('content')
    .update({
      content_url: newContentUrl,
      thumbnail_url: newThumbnailUrl,
      content_type: contentType,
      title: title,
      description: description,
      updated_at: new Date().toISOString()
    })
    .eq('id', existingContent.id);
  
  if (updateError) {
    console.error("Error updating content:", updateError);
    return false;
  }
  
  return true;
};
